### ISSUE TITLE
Wellformedness of OWL-logic definitions

### ISSUE THREAD

**Issue by lfurrer** [UCDenver-ccp/CRAFT#15]
The extended annotation sets contain added classes that don't have an "is_a" entry.
Instead, their definition is a logical expression in OWL syntax which typically contains references to other classes (IDs).

When I tried to extract these references from the definitions, I encountered a couple of problems.
I didn't use an OWL reasoner, but rather used a scripting approach, since I don't need the full logic, but really just the mentions of other entities.
However, I suspect that a more thorough examination of the definition statements would also suffer from the issues below.

## Newlines
Some definitions contain newlines, as in the following stanza taken from GO_BP_EXT (after the second "or"):

    [Term]
    id: GO_EXT:biological_direction_or_guidance
    name: biological direction/guidance
    namespace: biological_process
    def: "GO:'biological regulation' or (BFO:occurrent and causally_effects_or_influences some BFO:entity) or
    (GO_EXT:biological_movement and causally_effected_or_influenced_by some BFO:entity)"
    synonym: "biological direction" EXACT []
    synonym: "biological guidance" EXACT []

I believe this is also a violation of the OBO format, as these entries also produce warnings when running the official evaluation suite.
It's not so hard to fix this during parsing (at least with Python's iterators), but it looks like this is unintentional.

## References by name
Some classes are referred to by ID (eg. `GO:0008150` or `SO_EXT:sequence_nullness`), while others use the name of the concept, sometimes enclosed in single quotes (eg. `SO_EXT:chromosomal_transposition` or `GO:'regulation of biological quality'`).
Using the name is certainly more human-friendly than using a numeric ID, but I think it's problematic in the following three cases:

### Unescaped single quotes inside single quotes
Some names already contain single quotes, which aren't escaped when put inside a pair of single quotes:

    CHEBI:'GMP 3'-end residue'
    CHEBI:'2'-deoxyribonucleoside 5'-triphosphate'

It's unclear to me how this can be automatically parsed in a reliable way.
One could require that the closing quote needs to be followed by whitespace or end-of-string, but I'm not sure if this is sufficient.

### Ambiguous names
There are many instances where multiple concepts use the same name.
Sometimes the references in the OWL definitions use such an ambiguous name, such as

    GO:'establishment of localization'

which matches three different concepts:

    GO_EXT:biological_movement_or_translocation_process
    GO_EXT:biological_recruitment
    GO_EXT:biological_translocation_entity_or_process

### Non-existing names
Sometimes, the name used can't be found:

    GO:'muscle tissue develoment'
    SO_EXT:'genetic marker'

The first case is clearly a typo.
In the second case (`SO:0001645`), the preferred name is "genetic_marker", while "genetic marker" is listed as a synonym only.
If the name references can also refer to synonyms, not only the preferred name, then this will probably aggravate the ambiguity problem mentioned.

**Comment by lfurrer** [comment]
I feel that a lot of work has gone into the extended classes, but these little issues, in their sum, impede automatic processing (corner-case engineering just wouldn't end) – which is a real pity.
I'm happy to help improve on the situation, but maybe the creators have more efficient ways (tools, knowledge...) than I have.

**Comment by mikebada** [comment]
All of the creation and use of the extension classes for concept annotation is a new feature for v3 of the corpus.  We've put a lot of work into this, but much remains to be done.  As you've found, the logical definitions added as text definitions aren't totally ready for usage in reasoning tasks.  They've principally been added to help users understand the semantics of the extension classes.

However, there are text files included in the concept annotation directories that I think contain what you're looking for:  In each X+extensions directory (where X is one of {CHEBI, CL, GO_BP, GO_CC, GO_MF, MOP, NCBITaxon, PR, SO, UBERON}), there's a file named X_extension_classes_and_related_X_classes.txt (where X denotes these same namespaces), which is, as its name indicates, a mapping of each extension class of the given ontology to the most semantically related classes in the corresponding base ontology.  There's more information about these files, including a description of their simple file structure, in the [README](https://github.com/UCDenver-ccp/CRAFT/tree/master/concept-annotation) for the concept annotations.

**Comment by lfurrer** [comment]
Thanks, I think those files are exactly what I was looking for! Sometimes one looks past the closest things...

**Comment by bill-baumgartner** [comment]
Closing as this seems to be resolved. Feel free to reopen if necessary.
