### ISSUE TITLE
I can't convert the coreference annotation file to conll format using the command "boot coreference  convert -i"

### ISSUE THREAD

**Issue by huyongquan** [UCDenver-ccp/CRAFT#20]
when i use the command "boot coreference  convert -i" in mac-os, but the following error is reported
java.lang.IllegalArgumentException: No sentence/token annotations were detected in the input document. Unable to write the CoNLLCoref 2011/12 format without sentence and token annotations.
        clojure.lang.ExceptionInfo: No sentence/token annotations were detected in the input document. Unable to write the CoNLLCoref 2011/12 format without sentence and token annotations.

**Comment by paulin-mipt** [comment]
I am facing the same issue, using java 1.8 on MacOS.

I've also tried converting to BRAT format and this one finished successfully, so the data seems fine.

**Comment by paulin-mipt** [comment]
@huyongquan I believe I've found the answer to similar question here: https://github.com/UCDenver-ccp/CRAFT/issues/12#issuecomment-498110716

You also need to include `part-of-speech` in addition to `coreference` to add sentence/token annotations

**Comment by huyongquan** [comment]
It works now. Thanks you very much. @paulin-mipt
