### ISSUE TITLE
Issue reading the UIMA XMIs for coreference annotation

### ISSUE THREAD

**Issue by sameer-pradhan** [UCDenver-ccp/CRAFT#3]
I have been trying to view the CRAFT UIMA .XMI annotation and am unable to find a tool and/or the necessary type system files to be able to do it. 

Maybe I will try BART next, but since I already spent a few hours twiddling with this format, it would be nice if I could follow it through. Apparently the type system .xml file required to read the coreference annotation is not present in the GitHub repository (as mentioned in the top level README file). 

I tried to use the one from the SourceForge pre-release but that did not seem to work. I don't have much experience with UIMA, but my impression was that one could view the annotations using a viewer if one had the .xmi file and the corresponding type system .xml file. 

I can more or less understand the annotation by looking at the XML inside the XMI file but did not want to make any assumptions that might lead me to a corrupted version of the annotation. Any help you can provide in this regard would be very much appreciated.

**Comment by tuh8888** [comment]
This type system file should work for all of the UIMA XMI annotation files. https://github.com/UCDenver-ccp/CRAFT/blob/master/ontology-concepts/CHEBI/CHEBI%2Bextensions/uima/CcpTypeSystem.xml

It does not appear to be located in the "ontology-concepts/all" UIMA directories, but should be. Let me know if that works

**Comment by sameer-pradhan** [comment]
Thanks! Let me try that.
I am a chronic UIMA novice and am hoping that this should work with the annotationViewer.sh script that is provided by the UIMA SDK.

**Comment by sameer-pradhan** [comment]
Hmm... 
Using the tool spawned by the annotationViewer.sh script, I am unable to read the documents with the above type system. The below image shows a screenshot. I am using UIMA SDK 2.10.3.

![image](https://user-images.githubusercontent.com/9543518/44935908-925ed200-ad40-11e8-9a8a-be23c180d684.png)

**Comment by sameer-pradhan** [comment]
I also tried opening it using the CVD tool (using cvd.sh script). It seems to show the spans but I still cannot seem to get a sense of how I can look at the coreference chain...

**Comment by tuh8888** [comment]
If you are just interested in viewing the annotations, I recommend using [Knowtator](https://github.com/UCDenver-ccp/Knowtator-2.0). I am not familiar enough with Apache UIMA SDK to help you view them on that platform

**Comment by sameer-pradhan** [comment]
I started with UIMA hoping it was the simplest :-)
Let me try knowtator. What is the difference between knowtator and knowtator-2?
Are these different main versions of knowtator?

Viewing was the first step. Eventually I would like to read the annotations programmatically.

**Comment by tuh8888** [comment]
That's makes sense since UIMA has been the standard for a while now. I just haven't used it enough myself to be sure and those files should be UIMA compatible. Right now, Knowtator is what I can provide you the most assistance with.

Knowtator was a plugin for Protege 3.3.1 and last updated in 2008. Knowtator 2 is a redesign I am actively working on that works with the newest version of Protege and features a graph viewer for viewing relations between annotations (including the coreference chains you are interested in). The instructions for installing Knowtator 2 with Protege are included in the README. 

I think the Knowtator file type should be easier for programmatically reading the annotations since it is a fairly simple XML file.

**Comment by sameer-pradhan** [comment]
Found that Knowtator 2.0 is the version in this GitHub organization.
Tried installing, but gets compilation errors. I have submitted an issue on the Knowtator repository.
If you have a pre-compiled .jar file for Knowtator 2.0, it could save me some time

**Comment by tuh8888** [comment]
Pre-compiled jar is located [here](https://github.com/UCDenver-ccp/Knowtator-2.0/releases)

**Comment by sameer-pradhan** [comment]
Thanks!

**Comment by sameer-pradhan** [comment]
Hmm. copied the knowtator-2.1.3.jar to the Contents/Java/plugins folder of Protege-5.2.0.
However, restarting Protege gives the following error:

![image](https://user-images.githubusercontent.com/9543518/44937871-74499f80-ad49-11e8-9948-9f7085b5cb01.png)

Protege 5.2.0 by itself does work before copying the knowtator .jar file

**Comment by tuh8888** [comment]
During installation on a Mac, sometimes users copy a link to the jar file into the Contents/Java/plugins folder and not the jar file itself. Can you check that first? 

Second, do you see the other plugins in that folder (ontograf, owlviz, cellfie, sparql-query, etc.)? If not, verify it's the right plugins folder (confusingly, there's a few of them for Protege).

**Comment by sameer-pradhan** [comment]
I believe I copied it in the right place.


/Users/pradhan/Downloads/Protege-5.2.0/Protégé.app/Contents/Java/plugins/
├── cellfie-2.1.0.jar
├── code-generation-2.0.0.jar
├── existentialquery-2.0.0.jar
├── explanation-workbench-3.0.0.jar
├── knowtator-2.1.3.jar
├── ontograf-2.0.3.jar
├── org.coode.dlquery-4.0.1.jar
├── org.semanticweb.hermit-1.3.8.413.jar
├── owldoc-3.0.3.jar
├── owlviz-5.0.3.jar
├── rdf-library-2.0.2.jar
├── sparql-query-plugin-2.0.1.jar
└── swrltab-plugin-1.0.3.jar

0 directories, 13 files

**Comment by sameer-pradhan** [comment]
Ok. I got Protege version 5.1.0 to work with the knowtator 2.1.3 plugin.
Now, I am trying to open an annotation file but don't seem to see any annotations.
I simply did File->Open-> and opened the *-knowtator.xml file inside the knowtator-2 folder
Is that the right way, or should I be doing something else?

**Comment by tuh8888** [comment]
That looks right. When most Mac users install Protege, it goes under the /Applications folder. But I don't think that should matter. That JAR file appears to work for me and others in my lab have have used that same download on their Macs. All I can think of is to check the Protege installation or retry downloading the Jar

**Comment by tuh8888** [comment]
Everything to manage Knowtator projects should be done in the Knowtator view by clicking "Knowtator Project"
![knowtator_project button](https://user-images.githubusercontent.com/13961671/44938434-35f9b380-ad3c-11e8-815f-279a8b833991.PNG)

See [here](https://github.com/UCDenver-ccp/Knowtator-2.0#setup) for how to setup the Knowtator view

**Comment by sameer-pradhan** [comment]
I now see the Knowtator tab.
I am opening the  .knowtator project file inside the CRAFT annotations.
IS that what I should be doing? Or should I be creating a new profile, and project and then importing the anntoations?

**Comment by tuh8888** [comment]
Opening the .knowtator file is correct. It may take a minute to load the coreference annotations since there are so many of them for each document.  Thank you for your patience through the setup process.

**Comment by sameer-pradhan** [comment]
I am getting closer...

**Comment by sameer-pradhan** [comment]
The problem was probably the number of documents.
I delete all and kept only one document and was able to open the annotations

**Comment by sameer-pradhan** [comment]
However, now I am not sure how to look at the IDENTITY chains. 
Below is the screenshot of what I am seeing. I tried selecting multiple spans but every time it only highlights one span and I cannot visualize the coreference chain...

What I am doing wrong?

![image](https://user-images.githubusercontent.com/9543518/44939341-65b3b600-ad52-11e8-8adf-d09f55bd9079.png)

**Comment by sameer-pradhan** [comment]
Okay, I think I now seem to be able to view the graph version (image below). Is this the right view?
![image](https://user-images.githubusercontent.com/9543518/44939490-a06a1e00-ad53-11e8-9efa-d376d23d598c.png)

**Comment by tuh8888** [comment]
Yes, that view should work. Scroll to the right to see each chain (the head node). Clicking on the nodes should take you to their locations in the article. You should be able to drag and rearrange as you see fit. Clicking "Apply Layout" will reset them to their original locations.

**Comment by bill-baumgartner** [comment]
Closing this issue. Feel free to re-open if necessary.
