### ISSUE TITLE
Making version clear

### ISSUE THREAD

**Issue by KevinBretonnelCohen** [UCDenver-ccp/CRAFT#6]
What would be a good way to make clear to someone who has come to the repository what version they are looking at?

**Comment by bill-baumgartner** [comment]
The best place to look for stable versions of CRAFT is the official [releases](https://github.com/UCDenver-ccp/CRAFT/releases) page. A reference to this has been added to the main project README.

**Comment by bill-baumgartner** [comment]
Closing this issue. Feel free to re-open if necessary.
