### ISSUE TITLE
Last sentence missing in 14611657.tree.conllu

### ISSUE THREAD

**Issue by spyysalo** [UCDenver-ccp/CRAFT#9]
The last lines in [14611657.txt](https://github.com/UCDenver-ccp/CRAFT/blob/master/articles/txt/14611657.txt) are

```
Summary of cDNA screen for each library and probe.

Probe names comprise the names of the two primers and the annealing temperature used during PCR to generate the probes, separated by underscores
```

but the corresponding `.tree.conllu` file ([14611657.tree.conllu](https://github.com/UCDenver-ccp/CRAFT/blob/master/structural-annotation/dependency/conllu/14611657.tree.conllu)) ends with

```
1	Summary	summary	NN	_	_	0	root	_	_
2	of	of	IN	_	_	1	prep	_	_
3	cDNA	cdna	NN	_	_	4	compound	_	_
4	screen	screen	NN	_	_	2	pobj	_	_
5	for	for	IN	_	_	1	prep	_	_
6	each	each	DT	_	_	7	det	_	_
7	library	library	NN	_	_	5	pobj	_	_
8	and	and	CC	_	_	7	cc	_	_
9	probe	probe	NN	_	_	7	conj	_	_
10	.	.	.	_	_	1	punct	_	_
```

i.e. the sentence "*Probe names comprise the names of the two primers ...*" is missing.

This appears to be missing also from the PTB parse [14611657.tree](https://github.com/UCDenver-ccp/CRAFT/blob/master/structural-annotation/treebank/penn/14611657.tree).

**Comment by bill-baumgartner** [comment]
[Release v3.1.1](https://github.com/UCDenver-ccp/CRAFT/releases/tag/v3.1.1) includes the parse for the missing sentence for document 14611657. Thanks again for pointing this out.

**Comment by spyysalo** [comment]
Thanks for the fix!
